### ISSUE TITLE
Error executing action `install` on resource 'chef_gem[mysql2]'

### ISSUE THREAD

**Issue by xbeta** [Banno/artifactory#7]
```
[2015-05-04T22:59:17+00:00] WARN: Cloning resource attributes for directory[/etc] from prior resource (CHEF-3694)
[2015-05-04T22:59:17+00:00] WARN: Previous directory[/etc]: /var/chef/cache/cookbooks/sumologic-collector/recipes/sumoconf.rb:58:in `from_file'
[2015-05-04T22:59:17+00:00] WARN: Current  directory[/etc]: /var/chef/cache/cookbooks/sumologic-collector/recipes/sumojson.rb:59:in `from_file'
[2015-05-04T22:59:17+00:00] WARN: Cloning resource attributes for package[unzip] from prior resource (CHEF-3694)
[2015-05-04T22:59:17+00:00] WARN: Previous package[unzip]: /var/chef/cache/cookbooks/java_ext/recipes/jce.rb:13:in `from_file'
[2015-05-04T22:59:17+00:00] WARN: Current  package[unzip]: /var/chef/cache/cookbooks/artifactory/recipes/default.rb:5:in `from_file'
Recipe: artifactory::mysql
  * chef_gem[mysql2] action install

    ================================================================================
    Error executing action `install` on resource 'chef_gem[mysql2]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/chef/embedded/bin/gem install mysql2 -q --no-rdoc --no-ri -v "0.3.18" ----
    STDOUT: Building native extensions.  This could take a while...
    STDERR: ERROR:  Error installing mysql2:
    	ERROR: Failed to build gem native extension.

        /opt/chef/embedded/bin/ruby extconf.rb
    checking for ruby/thread.h... no
    checking for rb_thread_blocking_region()... yes
    checking for rb_wait_for_single_fd()... yes
    checking for rb_hash_dup()... yes
    checking for rb_intern3()... yes
    checking for mysql_query() in -lmysqlclient... no
    checking for main() in -lm... yes
    checking for mysql_query() in -lmysqlclient... no
    checking for main() in -lz... yes
    checking for mysql_query() in -lmysqlclient... no
    checking for main() in -lsocket... no
    checking for mysql_query() in -lmysqlclient... no
    checking for main() in -lnsl... yes
    checking for mysql_query() in -lmysqlclient... no
    checking for main() in -lmygcc... no
    checking for mysql_query() in -lmysqlclient... no
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of
    necessary libraries and/or headers.  Check the mkmf.log file for more
    details.  You may need configuration options.

    Provided configuration options:
    	--with-opt-dir
    	--with-opt-include
    	--without-opt-include=${opt-dir}/include
    	--with-opt-lib
    	--without-opt-lib=${opt-dir}/lib
    	--with-make-prog
    	--without-make-prog
    	--srcdir=.
    	--curdir
    	--ruby=/opt/chef/embedded/bin/ruby
    	--with-mysql-dir
    	--without-mysql-dir
    	--with-mysql-include
    	--without-mysql-include=${mysql-dir}/include
    	--with-mysql-lib
    	--without-mysql-lib=${mysql-dir}/lib
    	--with-mysql-config
    	--without-mysql-config
    	--with-mysql-dir
    	--without-mysql-dir
    	--with-mysql-include
    	--without-mysql-include=${mysql-dir}/include
    	--with-mysql-lib
    	--without-mysql-lib=${mysql-dir}/lib
    	--with-mysqlclientlib
    	--without-mysqlclientlib
    	--with-mlib
    	--without-mlib
    	--with-mysqlclientlib
    	--without-mysqlclientlib
    	--with-zlib
    	--without-zlib
    	--with-mysqlclientlib
    	--without-mysqlclientlib
    	--with-socketlib
    	--without-socketlib
    	--with-mysqlclientlib
    	--without-mysqlclientlib
    	--with-nsllib
    	--without-nsllib
    	--with-mysqlclientlib
    	--without-mysqlclientlib
    	--with-mygcclib
    	--without-mygcclib
    	--with-mysqlclientlib
    	--without-mysqlclientlib


    Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mysql2-0.3.18 for inspection.
    Results logged to /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mysql2-0.3.18/ext/mysql2/gem_make.out
    ---- End output of /opt/chef/embedded/bin/gem install mysql2 -q --no-rdoc --no-ri -v "0.3.18" ----
    Ran /opt/chef/embedded/bin/gem install mysql2 -q --no-rdoc --no-ri -v "0.3.18" returned 1

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/artifactory/recipes/mysql.rb:25:in `from_file'
    /var/chef/cache/cookbooks/artifactory/recipes/_database.rb:2:in `from_file'
    /var/chef/cache/cookbooks/artifactory/recipes/default.rb:20:in `from_file'
    /var/chef/cache/cookbooks/my-artifactory/recipes/default.rb:22:in `from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/artifactory/recipes/mysql.rb

     25: chef_gem "mysql2" do
     26:   action :install
     27: end
     28:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/artifactory/recipes/mysql.rb:25:in `from_file'

    chef_gem("mysql2") do
      provider Chef::Provider::Package::Rubygems
      action [:install]
      retries 0
      retry_delay 2
      guard_interpreter :default
      package_name "mysql2"
      version "0.3.18"
      timeout 900
      gem_binary "/opt/chef/embedded/bin/gem"
      cookbook_name "artifactory"
      recipe_name "mysql"
    end


  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/my-artifactory/recipes/default.rb
  ================================================================================

  Mixlib::ShellOut::ShellCommandFailed
  ------------------------------------
  chef_gem[mysql2] (artifactory::mysql line 25) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
  ---- Begin output of /opt/chef/embedded/bin/gem install mysql2 -q --no-rdoc --no-ri -v "0.3.18" ----
  STDOUT: Building native extensions.  This could take a while...
  STDERR: ERROR:  Error installing mysql2:
  	ERROR: Failed to build gem native extension.

      /opt/chef/embedded/bin/ruby extconf.rb
  checking for ruby/thread.h... no
  checking for rb_thread_blocking_region()... yes
  checking for rb_wait_for_single_fd()... yes
  checking for rb_hash_dup()... yes
  checking for rb_intern3()... yes
  checking for mysql_query() in -lmysqlclient... no
  checking for main() in -lm... yes
  checking for mysql_query() in -lmysqlclient... no
  checking for main() in -lz... yes
  checking for mysql_query() in -lmysqlclient... no
  checking for main() in -lsocket... no
  checking for mysql_query() in -lmysqlclient... no
  checking for main() in -lnsl... yes
  checking for mysql_query() in -lmysqlclient... no
  checking for main() in -lmygcc... no
  checking for mysql_query() in -lmysqlclient... no
  *** extconf.rb failed ***
  Could not create Makefile due to some reason, probably lack of
  necessary libraries and/or headers.  Check the mkmf.log file for more
  details.  You may need configuration options.

  Provided configuration options:
  	--with-opt-dir
  	--with-opt-include
  	--without-opt-include=${opt-dir}/include
  	--with-opt-lib
  	--without-opt-lib=${opt-dir}/lib
  	--with-make-prog
  	--without-make-prog
  	--srcdir=.
  	--curdir
  	--ruby=/opt/chef/embedded/bin/ruby
  	--with-mysql-dir
  	--without-mysql-dir
  	--with-mysql-include
  	--without-mysql-include=${mysql-dir}/include
  	--with-mysql-lib
  	--without-mysql-lib=${mysql-dir}/lib
  	--with-mysql-config
  	--without-mysql-config
  	--with-mysql-dir
  	--without-mysql-dir
  	--with-mysql-include
  	--without-mysql-include=${mysql-dir}/include
  	--with-mysql-lib
  	--without-mysql-lib=${mysql-dir}/lib
  	--with-mysqlclientlib
  	--without-mysqlclientlib
  	--with-mlib
  	--without-mlib
  	--with-mysqlclientlib
  	--without-mysqlclientlib
  	--with-zlib
  	--without-zlib
  	--with-mysqlclientlib
  	--without-mysqlclientlib
  	--with-socketlib
  	--without-socketlib
  	--with-mysqlclientlib
  	--without-mysqlclientlib
  	--with-nsllib
  	--without-nsllib
  	--with-mysqlclientlib
  	--without-mysqlclientlib
  	--with-mygcclib
  	--without-mygcclib
  	--with-mysqlclientlib
  	--without-mysqlclientlib


  Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mysql2-0.3.18 for inspection.
  Results logged to /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mysql2-0.3.18/ext/mysql2/gem_make.out
  ---- End output of /opt/chef/embedded/bin/gem install mysql2 -q --no-rdoc --no-ri -v "0.3.18" ----
  Ran /opt/chef/embedded/bin/gem install mysql2 -q --no-rdoc --no-ri -v "0.3.18" returned 1

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/artifactory/recipes/mysql.rb:25:in `from_file'
    /var/chef/cache/cookbooks/artifactory/recipes/_database.rb:2:in `from_file'
    /var/chef/cache/cookbooks/artifactory/recipes/default.rb:20:in `from_file'
    /var/chef/cache/cookbooks/my-artifactory/recipes/default.rb:22:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/artifactory/recipes/mysql.rb:

   18:  # Install MySQL client
   19:  mysql_client 'default' do
   20:    action :create
   21:    notifies :install, 'chef_gem[mysql2]', :immediately
   22:  end
   23:
   24:  # NOTE: database cookbook required to use 'mysql2' gem to be installed
   25>> chef_gem "mysql2" do
   26:    action :install
   27:  end
   28:
   29:  # Install the MySQL server on the same box
   30:  template '/etc/mysql/conf.d/artifactory.cnf' do
   31:    owner node['artifactory']['user']
   32:    group node['artifactory']['user']
   33:    source 'artifactory.cnf.erb'
   34:    notifies :restart, 'mysql_service[default]'


  Running handlers:
[2015-05-04T22:59:25+00:00] ERROR: Running exception handlers
[2015-05-04T22:59:25+00:00] ERROR: Report handler Chef::Handler::Datadog raised #<NoMethodError: undefined method `length' for nil:NilClass>
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-handler-datadog-0.6.0/lib/chef/handler/datadog.rb:196:in `emit_metrics_to_datadog'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-handler-datadog-0.6.0/lib/chef/handler/datadog.rb:27:in `report'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:226:in `run_report_unsafe'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:214:in `run_report_safely'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:118:in `block in run_exception_handlers'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `each'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `run_exception_handlers'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:127:in `block in <class:Handler>'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:133:in `call'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:133:in `block in run_failed'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:132:in `each'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:132:in `run_failed'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:447:in `rescue in do_run'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:459:in `do_run'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:213:in `block in run'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:207:in `fork'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:207:in `run'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:236:in `run_chef_client'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:338:in `block in run_application'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:327:in `loop'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:327:in `run_application'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:55:in `run'
[2015-05-04T22:59:25+00:00] ERROR: /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
[2015-05-04T22:59:25+00:00] ERROR: /usr/bin/chef-client:38:in `load'
[2015-05-04T22:59:25+00:00] ERROR: /usr/bin/chef-client:38:in `<main>'
    - Chef::Handler::Datadog
  Running handlers complete
[2015-05-04T22:59:25+00:00] ERROR: Exception handlers complete
[2015-05-04T22:59:25+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
  Chef Client failed. 2 resources updated in 15.501009929 seconds
[2015-05-04T22:59:25+00:00] ERROR: chef_gem[mysql2] (artifactory::mysql line 25) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/gem install mysql2 -q --no-rdoc --no-ri -v "0.3.18" ----
STDOUT: Building native extensions.  This could take a while...
STDERR: ERROR:  Error installing mysql2:
	ERROR: Failed to build gem native extension.

    /opt/chef/embedded/bin/ruby extconf.rb
checking for ruby/thread.h... no
checking for rb_thread_blocking_region()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lm... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lz... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lsocket... no
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lnsl... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lmygcc... no
checking for mysql_query() in -lmysqlclient... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/chef/embedded/bin/ruby
	--with-mysql-dir
	--without-mysql-dir
	--with-mysql-include
	--without-mysql-include=${mysql-dir}/include
	--with-mysql-lib
	--without-mysql-lib=${mysql-dir}/lib
	--with-mysql-config
	--without-mysql-config
	--with-mysql-dir
	--without-mysql-dir
	--with-mysql-include
	--without-mysql-include=${mysql-dir}/include
	--with-mysql-lib
	--without-mysql-lib=${mysql-dir}/lib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-mlib
	--without-mlib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-zlib
	--without-zlib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-socketlib
	--without-socketlib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-nsllib
	--without-nsllib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-mygcclib
	--without-mygcclib
	--with-mysqlclientlib
	--without-mysqlclientlib


Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mysql2-0.3.18 for inspection.
Results logged to /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mysql2-0.3.18/ext/mysql2/gem_make.out
---- End output of /opt/chef/embedded/bin/gem install mysql2 -q --no-rdoc --no-ri -v "0.3.18" ----
Ran /opt/chef/embedded/bin/gem install mysql2 -q --no-rdoc --no-ri -v "0.3.18" returned 1
[2015-05-04T22:59:25+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by xbeta** [comment]
Probably related to this: https://github.com/sinfomicien/mysql2_chef_gem/issues/3
